window.themes = [
  {
    "name": "Default",
    "curveType": "hypotrochoid",
    "outer": 180,
    "inner": 80,
    "center": 60,
    "points": 12,
    "scale": 1,
    "layers": 2,
    "offset": "radius",
    "offsetAmount": 0.06,
    "speed": 0.02,
    "trail": 120,
    "lineWeight": 1.6,
    "lineThinning": 0.7,
    "hue": 35,
    "spread": 120,
    "isBuiltIn": true
  },
  {
    "name": "Rose",
    "curveType": "rose",
    "outer": 200,
    "inner": 100,
    "points": 7,
    "scale": 1.2,
    "layers": 1,
    "speed": 0.01,
    "trail": 200,
    "lineWeight": 1,
    "lineThinning": 0.5,
    "hue": 0,
    "spread": 60,
    "isBuiltIn": true
  },
  {
    "name": "Lissajous",
    "curveType": "lissajous",
    "outer": 250,
    "inner": 200,
    "center": 0.5,
    "points": 1,
    "scale": 1,
    "layers": 1,
    "speed": 0.01,
    "trail": 300,
    "lineWeight": 2,
    "lineThinning": 0.2,
    "hue": 120,
    "spread": 0,
    "isBuiltIn": true
  },
  {
    "name": "Petal Bloom",
    "curveType": "rose",
    "outer": 150,
    "inner": 40,
    "center": 120,
    "points": 8,
    "hue": 300,
    "spread": 60,
    "speed": 0.015,
    "layers": 2,
    "offset": "radius",
    "reverse": false,
    "dual": false,
    "isBuiltIn": true
  },
  {
    "name": "Infinity Weave",
    "curveType": "lissajous",
    "outer": 220,
    "inner": 180,
    "center": 80,
    "points": 6,
    "hue": 200,
    "spread": 120,
    "speed": 0.01,
    "layers": 3,
    "offset": "phase",
    "reverse": true,
    "dual": true,
    "secondary": "hypotrochoid",
    "dualMode": "combine",
    "isBuiltIn": true
  },
  {
    "name": "Neon Spinner",
    "curveType": "epitrochoid",
    "outer": 180,
    "inner": 90,
    "center": 100,
    "points": 16,
    "hue": 50,
    "spread": 180,
    "speed": 0.025,
    "layers": 2,
    "offset": "rotation",
    "reverse": false,
    "dual": true,
    "secondary": "superformula",
    "dualMode": "blend",
    "isBuiltIn": true
  },
  {
    "name": "Deep Bloom",
    "curveType": "hypotrochoid",
    "outer": 200,
    "inner": 70,
    "center": 150,
    "points": 10,
    "hue": 160,
    "spread": 100,
    "speed": 0.018,
    "layers": 1,
    "offset": "radius",
    "reverse": false,
    "dual": false,
    "isBuiltIn": true
  },
  {
    "name": "Starburst",
    "curveType": "rose",
    "outer": 260,
    "inner": 60,
    "center": 40,
    "points": 20,
    "hue": 10,
    "spread": 200,
    "speed": 0.02,
    "layers": 4,
    "offset": "rotation",
    "reverse": true,
    "dual": true,
    "secondary": "epitrochoid",
    "dualMode": "alternate",
    "isBuiltIn": true
  },
  {
    "name": "Cosmic Bloom",
    "curveType": "hypotrochoid",
    "outer": 250,
    "inner": 100,
    "center": 80,
    "points": 32,
    "hue": 280,
    "spread": 100,
    "speed": 0.005,
    "layers": 3,
    "offset": "phase",
    "reverse": true,
    "dual": false,
    "isBuiltIn": true
  },
  {
    "name": "Electric Spiro",
    "curveType": "epitrochoid",
    "outer": 200,
    "inner": 50,
    "center": 120,
    "points": 3,
    "hue": 180,
    "spread": 30,
    "speed": 0.03,
    "layers": 1,
    "offset": "radius",
    "reverse": false,
    "dual": false,
    "isBuiltIn": true
  },
  {
    "name": "Gentle Rose",
    "curveType": "rose",
    "outer": 150,
    "inner": 50,
    "center": 0,
    "points": 5,
    "hue": 330,
    "spread": 20,
    "speed": 0.01,
    "layers": 1,
    "offset": "radius",
    "reverse": false,
    "dual": false,
    "isBuiltIn": true
  },
  {
    "name": "Dancing Lissajous",
    "curveType": "lissajous",
    "outer": 200,
    "inner": 150,
    "center": 0.2,
    "points": 1,
    "hue": 240,
    "spread": 0,
    "speed": 0.02,
    "layers": 1,
    "offset": "radius",
    "reverse": false,
    "dual": false,
    "isBuiltIn": true
  },
  {
    "name": "Crystal Superformula",
    "curveType": "superformula",
    "outer": 200,
    "inner": 0,
    "center": 0,
    "points": 1,
    "hue": 180,
    "spread": 0,
    "speed": 0.01,
    "layers": 1,
    "offset": "radius",
    "reverse": false,
    "dual": false,
    "isBuiltIn": true
  },
  {
    "name": "Harmonic Pendulum",
    "curveType": "harmonograph",
    "outer": 200,
    "inner": 100,
    "center": 0,
    "points": 1,
    "hue": 150,
    "spread": 0,
    "speed": 0.005,
    "layers": 1,
    "offset": "radius",
    "reverse": false,
    "dual": false,
    "isBuiltIn": true
  },
  {
    "name": "Inner Fire",
    "curveType": "hypocycloid",
    "outer": 200,
    "inner": 80,
    "center": 0,
    "points": 1,
    "hue": 0,
    "spread": 30,
    "speed": 0.01,
    "layers": 1,
    "offset": "radius",
    "reverse": false,
    "dual": false,
    "isBuiltIn": true
  },
  {
    "name": "Galactic Swirl",
    "curveType": "epicycloid",
    "outer": 150,
    "inner": 30,
    "center": 0,
    "points": 1,
    "hue": 270,
    "spread": 60,
    "speed": 0.01,
    "layers": 8,
    "offset": "rotation",
    "reverse": true,
    "dual": false,
    "isBuiltIn": true
  },
  {
    "name": "Rolling Hills",
    "curveType": "cycloid",
    "outer": 0,
    "inner": 100,
    "center": 0,
    "points": 1,
    "hue": 120,
    "spread": 0,
    "speed": 0.01,
    "layers": 1,
    "offset": "radius",
    "reverse": false,
    "dual": false,
    "isBuiltIn": true
  },
  {
    "name": "Comet's Tail",
    "curveType": "trochoid",
    "outer": 0,
    "inner": 100,
    "center": 150,
    "points": 1,
    "hue": 180,
    "spread": 0,
    "speed": 0.03,
    "trail": 300,
    "layers": 1,
    "offset": "radius",
    "reverse": false,
    "dual": false,
    "isBuiltIn": true
  },
  {
    "name": "Aurora Drift",
    "curveType": "hypotrochoid",
    "outer": 260,
    "inner": 110,
    "center": 140,
    "points": 18,
    "hue": 200,
    "spread": 160,
    "speed": 0.008,
    "layers": 3,
    "offset": "phase",
    "reverse": false,
    "dual": false,
    "isBuiltIn": true
  },
  {
    "name": "Solar Bloom",
    "curveType": "rose",
    "outer": 300,
    "inner": 80,
    "center": 60,
    "points": 12,
    "hue": 35,
    "spread": 90,
    "speed": 0.015,
    "layers": 4,
    "offset": "rotation",
    "reverse": true,
    "dual": true,
    "secondary": "epitrochoid",
    "dualMode": "blend",
    "isBuiltIn": true
  },
  {
    "name": "Quantum Echo",
    "curveType": "lissajous",
    "outer": 240,
    "inner": 190,
    "center": 0.3,
    "points": 1,
    "hue": 260,
    "spread": 0,
    "speed": 0.006,
    "layers": 2,
    "offset": "phase",
    "reverse": false,
    "dual": true,
    "secondary": "superformula",
    "dualMode": "alternate",
    "isBuiltIn": true
  },
  {
    "name": "Mirage Spiral",
    "curveType": "epitrochoid",
    "outer": 220,
    "inner": 40,
    "center": 150,
    "points": 22,
    "hue": 150,
    "spread": 200,
    "speed": 0.02,
    "layers": 3,
    "offset": "radius",
    "reverse": true,
    "dual": false,
    "isBuiltIn": true
  },
  {
    "name": "Velvet Pulse",
    "curveType": "superformula",
    "outer": 180,
    "inner": 0,
    "center": 0,
    "points": 1,
    "hue": 320,
    "spread": 0,
    "speed": 0.012,
    "layers": 2,
    "offset": "rotation",
    "reverse": false,
    "dual": false,
    "isBuiltIn": true
  },
  {
    "name": "Atomic Flower",
    "curveType": "rose",
    "outer": 210,
    "inner": 60,
    "center": 40,
    "points": 24,
    "hue": 90,
    "spread": 140,
    "speed": 0.018,
    "layers": 5,
    "offset": "phase",
    "reverse": true,
    "dual": true,
    "secondary": "hypotrochoid",
    "dualMode": "combine",
    "isBuiltIn": true
  },
  {
    "name": "Midnight Lens",
    "curveType": "hypocycloid",
    "outer": 220,
    "inner": 45,
    "center": 0,
    "points": 1,
    "hue": 260,
    "spread": 40,
    "speed": 0.01,
    "layers": 1,
    "offset": "rotation",
    "reverse": false,
    "dual": false,
    "isBuiltIn": true
  },
  {
    "name": "Ion Drift",
    "curveType": "epicycloid",
    "outer": 260,
    "inner": 70,
    "center": 0,
    "points": 1,
    "hue": 180,
    "spread": 120,
    "speed": 0.02,
    "layers": 6,
    "offset": "phase",
    "reverse": true,
    "dual": false,
    "isBuiltIn": true
  },
  {
    "name": "Dream Tides",
    "curveType": "trochoid",
    "outer": 0,
    "inner": 140,
    "center": 90,
    "points": 1,
    "hue": 280,
    "spread": 20,
    "speed": 0.009,
    "trail": 250,
    "layers": 2,
    "offset": "radius",
    "reverse": false,
    "dual": false,
    "isBuiltIn": true
  },
  {
    "name": "Hypernova",
    "curveType": "epitrochoid",
    "outer": 300,
    "inner": 100,
    "center": 200,
    "points": 30,
    "hue": 20,
    "spread": 260,
    "speed": 0.04,
    "layers": 3,
    "offset": "rotation",
    "reverse": true,
    "dual": true,
    "secondary": "superformula",
    "dualMode": "blend",
    "isBuiltIn": true
  },
  {
    "reverse": true,
    "n3": 1.7,
    "secondary": "astroid",
    "m": 6,
    "scale": 1,
    "d1": 0.0006,
    "lineWeight": 2.308876404256661,
    "trail": 105,
    "createdAt": "2025-11-19T15:32:28.606Z",
    "spread": 214,
    "d2": 0.0008,
    "speed": 0.034400812013793206,
    "f1": 2,
    "offsetAmount": 0.020154698969530798,
    "points": 8,
    "offset": "phase",
    "n1": 0.3,
    "layers": 6,
    "dualMode": "alternate",
    "hue": 258,
    "f2": 3,
    "lineThinning": 0.6858268186889726,
    "curveType": "ellipse",
    "inner": 99,
    "dual": true,
    "n2": 1.7,
    "outer": 352,
    "center": 197,
    "name": "The Chromatic Loom",
    "id": "6awBuSPvpCVFO2PeSSra",
    "isCommunity": true
  },
  {
    "spread": 302,
    "lineWeight": 2.3,
    "n3": 1.7,
    "dual": true,
    "f1": 2,
    "points": 31,
    "f2": 3,
    "secondary": "lissajous",
    "createdAt": "2025-11-18T00:51:40.795Z",
    "m": 6,
    "trail": 180,
    "offset": "phase",
    "hue": 161,
    "lineThinning": 0.13,
    "center": 207,
    "d2": 0.0008,
    "n2": 1.7,
    "offsetAmount": 0.2920241475265244,
    "n1": 0.3,
    "inner": 219,
    "name": "whoa",
    "scale": 1,
    "reverse": false,
    "outer": 303,
    "d1": 0.0006,
    "curveType": "ellipse",
    "dualMode": "combine",
    "speed": 0.021,
    "layers": 4,
    "id": "Mtq1T79YmQS3qVcfyepk",
    "isCommunity": true
  },
  {
    "inner": 84,
    "center": 55,
    "offset": "radius",
    "f2": 3,
    "n3": 1.7,
    "hue": 238,
    "dualMode": "blend",
    "n2": 1.7,
    "layers": 7,
    "m": 6,
    "d1": 0.0006,
    "curveType": "rose",
    "scale": 2,
    "f1": 2,
    "offsetAmount": 0.06,
    "trail": 10,
    "n1": 0.3,
    "reverse": false,
    "points": 23,
    "name": "Fireworks",
    "spread": 301,
    "speed": 0.015,
    "outer": 104,
    "createdAt": "2025-12-01T02:32:50.201Z",
    "lineThinning": 1,
    "d2": 0.0008,
    "lineWeight": 0.9,
    "secondary": "epitrochoid",
    "dual": true,
    "id": "RuoPpMWCakJ0IOKwa86o",
    "isCommunity": true
  },
  {
    "layers": 4,
    "m": 6,
    "dual": true,
    "f1": 2,
    "n1": 0.3,
    "offsetAmount": 0.38037885924783305,
    "lineThinning": 0.3116946965881665,
    "scale": 1.038135593220339,
    "reverse": false,
    "center": 181,
    "n3": 1.7,
    "d2": 0.0008,
    "offset": "phase",
    "trail": 173,
    "createdAt": "2025-11-22T15:12:21.540Z",
    "outer": 229,
    "spread": 255,
    "secondary": "cardioid",
    "d1": 0.0006,
    "name": "Like No Spirograph I ever made",
    "dualMode": "blend",
    "inner": 26,
    "hue": 31,
    "speed": 0.01091563744729656,
    "f2": 3,
    "curveType": "lissajous",
    "points": 4,
    "lineWeight": 0.9702613393068078,
    "n2": 1.7,
    "id": "U4Spo15G7TpVTPHvORmx",
    "isCommunity": true
  },
  {
    "offset": "radius",
    "d2": 0.0008,
    "f1": 2,
    "curveType": "harmonograph",
    "dualMode": "alternate",
    "secondary": "epitrochoid",
    "hue": 276,
    "lineWeight": 3.5,
    "inner": 118,
    "name": "Dashed",
    "reverse": false,
    "n3": 1.7,
    "lineThinning": 0.67,
    "outer": 116,
    "n1": 0.3,
    "dual": false,
    "m": 6,
    "offsetAmount": 0.5155209331078087,
    "speed": 0.04,
    "trail": 228,
    "d1": 0.0006,
    "n2": 1.7,
    "center": 68,
    "scale": 3.1410256410256414,
    "f2": 3,
    "createdAt": "2025-11-22T14:51:09.183Z",
    "points": 10,
    "spread": 206,
    "layers": 3,
    "id": "joj7tVRTNnns5vKJGTTA",
    "isCommunity": true
  },
  {
    "offset": "rotation",
    "hue": 358,
    "f2": 3,
    "points": 21,
    "name": "Star burst",
    "offsetAmount": 0.467039599944524,
    "inner": 218,
    "lineThinning": 0.14,
    "createdAt": "2025-11-17T23:15:18.086Z",
    "secondary": "trochoid",
    "reverse": false,
    "d1": 0.0006,
    "center": 22,
    "n3": 1.7,
    "spread": 89,
    "dualMode": "combine",
    "m": 6,
    "outer": 349,
    "curveType": "cycloid",
    "d2": 0.0008,
    "n2": 1.7,
    "layers": 3,
    "speed": 0.016,
    "lineWeight": 1.5,
    "trail": 153,
    "scale": 0.3318872017353579,
    "f1": 2,
    "dual": true,
    "n1": 0.3,
    "id": "k9BkeMWXDxP7bbOsc1J8",
    "isCommunity": true
  },
  {
    "curveType": "harmonograph",
    "offset": "phase",
    "center": 165,
    "scale": 0.8445205479452054,
    "dualMode": "blend",
    "d1": 0.0006,
    "spread": 111,
    "secondary": "superformula",
    "m": 6,
    "n3": 1.7,
    "f2": 3,
    "points": 5,
    "reverse": true,
    "hue": 124,
    "trail": 172,
    "outer": 240,
    "d2": 0.0008,
    "dual": false,
    "speed": 0.038,
    "n2": 1.7,
    "f1": 2,
    "lineThinning": 0.37,
    "inner": 125,
    "lineWeight": 2.9,
    "createdAt": "2025-11-17T23:10:21.830Z",
    "n1": 0.3,
    "offsetAmount": 0.06162674335192518,
    "layers": 3,
    "name": "DashedPent",
    "id": "vXnNDbpGVpCq0YKX9In1",
    "isCommunity": true
  },
  {
    "curveType": "ellipse",
    "n2": 1.7,
    "offsetAmount": 0.12012691347983805,
    "trail": 155,
    "createdAt": "2025-11-17T23:18:20.831Z",
    "d1": 0.0006,
    "dual": false,
    "spread": 320,
    "hue": 215,
    "name": "Interesting ",
    "speed": 0.015,
    "inner": 100,
    "n1": 0.3,
    "center": 27,
    "f2": 3,
    "lineWeight": 0.6,
    "d2": 0.0008,
    "n3": 1.7,
    "points": 7,
    "offset": "radius",
    "outer": 232,
    "secondary": "limacon",
    "reverse": true,
    "m": 6,
    "dualMode": "combine",
    "f1": 2,
    "layers": 6,
    "lineThinning": 0.56,
    "scale": 0.7304502369668247,
    "id": "w1jufWzXX65wKDZ4QciT",
    "isCommunity": true
  },
  {
    "name": "Prism Helix",
    "curveType": "lissajous",
    "outer": 260,
    "inner": 190,
    "center": 0.25,
    "points": 1,
    "hue": 45,
    "spread": 240,
    "speed": 0.012,
    "layers": 5,
    "offset": "rotation",
    "offsetAmount": 0.18,
    "reverse": false,
    "dual": true,
    "secondary": "epitrochoid",
    "dualMode": "blend",
    "lineWeight": 1.4,
    "lineThinning": 0.5,
    "trail": 180,
    "scale": 1,
    "isBuiltIn": false
  },
  {
    "name": "Oracle Bloom",
    "curveType": "rose",
    "outer": 220,
    "inner": 70,
    "center": 80,
    "points": 14,
    "hue": 260,
    "spread": 80,
    "speed": 0.006,
    "layers": 3,
    "offset": "phase",
    "offsetAmount": 0.12,
    "reverse": true,
    "dual": false,
    "lineWeight": 1,
    "lineThinning": 0.35,
    "trail": 240,
    "scale": 1.1,
    "isBuiltIn": false
  },
  {
    "name": "Tesla Coil",
    "curveType": "epicycloid",
    "outer": 180,
    "inner": 45,
    "center": 0,
    "points": 1,
    "hue": 200,
    "spread": 180,
    "speed": 0.04,
    "layers": 4,
    "offset": "rotation",
    "offsetAmount": 0.3,
    "reverse": false,
    "dual": false,
    "lineWeight": 2,
    "lineThinning": 0.6,
    "trail": 150,
    "scale": 1,
    "isBuiltIn": false
  },
  {
    "name": "Tideweaver",
    "curveType": "harmonograph",
    "outer": 250,
    "inner": 120,
    "center": 0.1,
    "points": 1,
    "hue": 170,
    "spread": 40,
    "speed": 0.007,
    "layers": 2,
    "offset": "phase",
    "offsetAmount": 0.05,
    "reverse": false,
    "dual": true,
    "secondary": "trochoid",
    "dualMode": "alternate",
    "lineWeight": 1.8,
    "lineThinning": 0.3,
    "trail": 200,
    "scale": 1.05,
    "isBuiltIn": false
  },
  {
    "name": "Lantern Spiral",
    "curveType": "hypotrochoid",
    "outer": 300,
    "inner": 140,
    "center": 200,
    "points": 18,
    "hue": 20,
    "spread": 100,
    "speed": 0.014,
    "layers": 3,
    "offset": "radius",
    "offsetAmount": 0.22,
    "reverse": true,
    "dual": false,
    "lineWeight": 1.3,
    "lineThinning": 0.4,
    "trail": 220,
    "scale": 1,
    "isBuiltIn": false
  },
  {
    "name": "Nebula Lens",
    "curveType": "superformula",
    "outer": 210,
    "inner": 0,
    "center": 0,
    "points": 1,
    "hue": 300,
    "spread": 0,
    "speed": 0.01,
    "layers": 4,
    "offset": "phase",
    "offsetAmount": 0.07,
    "reverse": false,
    "dual": true,
    "secondary": "lissajous",
    "dualMode": "blend",
    "lineWeight": 1,
    "lineThinning": 0.3,
    "trail": 260,
    "scale": 1.2,
    "isBuiltIn": false
  },
  {
    "name": "Third Eye",
    "curveType": "ellipse",
    "outer": 260,
    "inner": 130,
    "center": 100,
    "points": 4,
    "hue": 240,
    "spread": 20,
    "speed": 0.003,
    "layers": 2,
    "offset": "rotation",
    "offsetAmount": 0.04,
    "reverse": false,
    "dual": false,
    "lineWeight": 0.9,
    "lineThinning": 0.15,
    "trail": 300,
    "scale": 1,
    "isBuiltIn": false
  },
  {
    "name": "Ember Bloom",
    "curveType": "rose",
    "outer": 180,
    "inner": 40,
    "center": 30,
    "points": 9,
    "hue": 15,
    "spread": 60,
    "speed": 0.02,
    "layers": 5,
    "offset": "phase",
    "offsetAmount": 0.15,
    "reverse": true,
    "dual": false,
    "lineWeight": 1.1,
    "lineThinning": 0.9,
    "trail": 160,
    "scale": 1.3,
    "isBuiltIn": false
  },
  {
    "name": "Crystal Net",
    "curveType": "epitrochoid",
    "outer": 280,
    "inner": 60,
    "center": 160,
    "points": 26,
    "hue": 210,
    "spread": 260,
    "speed": 0.012,
    "layers": 6,
    "offset": "rotation",
    "offsetAmount": 0.28,
    "reverse": false,
    "dual": true,
    "secondary": "superformula",
    "dualMode": "combine",
    "lineWeight": 0.8,
    "lineThinning": 0.5,
    "trail": 200,
    "scale": 1,
    "isBuiltIn": false
  },
  {
    "name": "Verdant Pulse",
    "curveType": "hypocycloid",
    "outer": 220,
    "inner": 70,
    "center": 0,
    "points": 1,
    "hue": 110,
    "spread": 40,
    "speed": 0.01,
    "layers": 3,
    "offset": "radius",
    "offsetAmount": 0.09,
    "reverse": false,
    "dual": false,
    "lineWeight": 1.2,
    "lineThinning": 0.4,
    "trail": 180,
    "scale": 1,
    "isBuiltIn": false
  },

  /* ----------- 20 NEW THEMES BELOW ----------- */

  {
    "name": "Solar Veins",
    "curveType": "epicycloid",
    "outer": 240,
    "inner": 50,
    "center": 0,
    "points": 1,
    "hue": 40,
    "spread": 140,
    "speed": 0.018,
    "layers": 6,
    "offset": "rotation",
    "offsetAmount": 0.14,
    "reverse": true,
    "dual": false,
    "lineWeight": 1.3,
    "lineThinning": 0.4,
    "trail": 210,
    "scale": 1,
    "isBuiltIn": false
  },
  {
    "name": "Lunar Stitch",
    "curveType": "lissajous",
    "outer": 200,
    "inner": 150,
    "center": 0.4,
    "points": 1,
    "hue": 260,
    "spread": 0,
    "speed": 0.009,
    "layers": 3,
    "offset": "phase",
    "offsetAmount": 0.16,
    "reverse": false,
    "dual": false,
    "lineWeight": 0.9,
    "lineThinning": 0.22,
    "trail": 280,
    "scale": 1,
    "isBuiltIn": false
  },
  {
    "name": "Glass Orchid",
    "curveType": "superformula",
    "outer": 260,
    "inner": 0,
    "center": 0,
    "points": 1,
    "hue": 320,
    "spread": 10,
    "speed": 0.008,
    "layers": 5,
    "offset": "rotation",
    "offsetAmount": 0.09,
    "reverse": false,
    "dual": true,
    "secondary": "rose",
    "dualMode": "blend",
    "lineWeight": 1,
    "lineThinning": 0.4,
    "trail": 260,
    "scale": 1.2,
    "isBuiltIn": false
  },
  {
    "name": "Magnetar Spin",
    "curveType": "epitrochoid",
    "outer": 300,
    "inner": 90,
    "center": 180,
    "points": 20,
    "hue": 180,
    "spread": 200,
    "speed": 0.03,
    "layers": 3,
    "offset": "phase",
    "offsetAmount": 0.21,
    "reverse": true,
    "dual": false,
    "lineWeight": 1.4,
    "lineThinning": 0.6,
    "trail": 200,
    "scale": 1,
    "isBuiltIn": false
  },
  {
    "name": "Dragon Coil",
    "curveType": "trochoid",
    "outer": 0,
    "inner": 160,
    "center": 110,
    "points": 1,
    "hue": 25,
    "spread": 18,
    "speed": 0.025,
    "layers": 4,
    "offset": "radius",
    "offsetAmount": 0.18,
    "reverse": false,
    "dual": false,
    "lineWeight": 1.8,
    "lineThinning": 0.7,
    "trail": 260,
    "scale": 1.1,
    "isBuiltIn": false
  },
  {
    "name": "Silent Bloom",
    "curveType": "rose",
    "outer": 190,
    "inner": 35,
    "center": 60,
    "points": 13,
    "hue": 260,
    "spread": 40,
    "speed": 0.006,
    "layers": 2,
    "offset": "phase",
    "offsetAmount": 0.08,
    "reverse": false,
    "dual": false,
    "lineWeight": 0.9,
    "lineThinning": 0.5,
    "trail": 240,
    "scale": 1.1,
    "isBuiltIn": false
  },
  {
    "name": "Photon Web",
    "curveType": "hypotrochoid",
    "outer": 280,
    "inner": 110,
    "center": 150,
    "points": 24,
    "hue": 210,
    "spread": 180,
    "speed": 0.018,
    "layers": 6,
    "offset": "rotation",
    "offsetAmount": 0.26,
    "reverse": true,
    "dual": true,
    "secondary": "lissajous",
    "dualMode": "combine",
    "lineWeight": 1,
    "lineThinning": 0.5,
    "trail": 220,
    "scale": 1,
    "isBuiltIn": false
  },
  {
    "name": "Ribbonwind",
    "curveType": "harmonograph",
    "outer": 260,
    "inner": 130,
    "center": 0,
    "points": 1,
    "hue": 120,
    "spread": 0,
    "speed": 0.01,
    "layers": 3,
    "offset": "phase",
    "offsetAmount": 0.12,
    "reverse": false,
    "dual": false,
    "lineWeight": 1.6,
    "lineThinning": 0.33,
    "trail": 260,
    "scale": 0.9,
    "isBuiltIn": false
  },
  {
    "name": "Polar Flare",
    "curveType": "epicycloid",
    "outer": 180,
    "inner": 28,
    "center": 0,
    "points": 1,
    "hue": 300,
    "spread": 130,
    "speed": 0.023,
    "layers": 5,
    "offset": "rotation",
    "offsetAmount": 0.19,
    "reverse": true,
    "dual": false,
    "lineWeight": 1.2,
    "lineThinning": 0.4,
    "trail": 200,
    "scale": 1.1,
    "isBuiltIn": false
  },
  {
    "name": "Auric Halo",
    "curveType": "superformula",
    "outer": 240,
    "inner": 0,
    "center": 0,
    "points": 1,
    "hue": 38,
    "spread": 0,
    "speed": 0.009,
    "layers": 4,
    "offset": "phase",
    "offsetAmount": 0.11,
    "reverse": false,
    "dual": true,
    "secondary": "epitrochoid",
    "dualMode": "blend",
    "lineWeight": 1.1,
    "lineThinning": 0.45,
    "trail": 260,
    "scale": 1.2,
    "isBuiltIn": false
  },
  {
    "name": "Nightgrid",
    "curveType": "ellipse",
    "outer": 300,
    "inner": 140,
    "center": 85,
    "points": 6,
    "hue": 250,
    "spread": 30,
    "speed": 0.006,
    "layers": 2,
    "offset": "rotation",
    "offsetAmount": 0.1,
    "reverse": true,
    "dual": false,
    "lineWeight": 1.4,
    "lineThinning": 0.2,
    "trail": 280,
    "scale": 1,
    "isBuiltIn": false
  },
  {
    "name": "Thunder Rose",
    "curveType": "rose",
    "outer": 260,
    "inner": 80,
    "center": 30,
    "points": 17,
    "hue": 8,
    "spread": 180,
    "speed": 0.02,
    "layers": 5,
    "offset": "phase",
    "offsetAmount": 0.2,
    "reverse": true,
    "dual": false,
    "lineWeight": 1.7,
    "lineThinning": 0.55,
    "trail": 220,
    "scale": 1.3,
    "isBuiltIn": false
  },
  {
    "name": "Icicle Echo",
    "curveType": "epitrochoid",
    "outer": 210,
    "inner": 38,
    "center": 120,
    "points": 18,
    "hue": 210,
    "spread": 220,
    "speed": 0.014,
    "layers": 3,
    "offset": "radius",
    "offsetAmount": 0.12,
    "reverse": false,
    "dual": true,
    "secondary": "lissajous",
    "dualMode": "alternate",
    "lineWeight": 0.9,
    "lineThinning": 0.35,
    "trail": 200,
    "scale": 1,
    "isBuiltIn": false
  },
  {
    "name": "Serpentine Drift",
    "curveType": "trochoid",
    "outer": 0,
    "inner": 120,
    "center": 70,
    "points": 1,
    "hue": 150,
    "spread": 20,
    "speed": 0.016,
    "layers": 2,
    "offset": "rotation",
    "offsetAmount": 0.06,
    "reverse": false,
    "dual": false,
    "lineWeight": 1.2,
    "lineThinning": 0.4,
    "trail": 220,
    "scale": 1.1,
    "isBuiltIn": false
  },
  {
    "name": "Omega Spiral",
    "curveType": "hypocycloid",
    "outer": 260,
    "inner": 140,
    "center": 0,
    "points": 1,
    "hue": 285,
    "spread": 80,
    "speed": 0.01,
    "layers": 4,
    "offset": "radius",
    "offsetAmount": 0.1,
    "reverse": true,
    "dual": false,
    "lineWeight": 1.5,
    "lineThinning": 0.45,
    "trail": 240,
    "scale": 1,
    "isBuiltIn": false
  },
  {
    "name": "Shimmer Net",
    "curveType": "epicycloid",
    "outer": 180,
    "inner": 32,
    "center": 0,
    "points": 1,
    "hue": 260,
    "spread": 160,
    "speed": 0.02,
    "layers": 6,
    "offset": "phase",
    "offsetAmount": 0.25,
    "reverse": false,
    "dual": false,
    "lineWeight": 1.2,
    "lineThinning": 0.3,
    "trail": 180,
    "scale": 1.1,
    "isBuiltIn": false
  },
  {
    "name": "Sunken Bloom",
    "curveType": "rose",
    "outer": 220,
    "inner": 60,
    "center": 50,
    "points": 11,
    "hue": 165,
    "spread": 50,
    "speed": 0.009,
    "layers": 3,
    "offset": "phase",
    "offsetAmount": 0.12,
    "reverse": false,
    "dual": false,
    "lineWeight": 1,
    "lineThinning": 0.4,
    "trail": 260,
    "scale": 1.2,
    "isBuiltIn": false
  },
  {
    "name": "Fractal Wave",
    "curveType": "harmonograph",
    "outer": 220,
    "inner": 110,
    "center": 0,
    "points": 1,
    "hue": 200,
    "spread": 20,
    "speed": 0.007,
    "layers": 3,
    "offset": "phase",
    "offsetAmount": 0.08,
    "reverse": false,
    "dual": false,
    "lineWeight": 1.3,
    "lineThinning": 0.33,
    "trail": 300,
    "scale": 0.95,
    "isBuiltIn": false
  },
  {
    "name": "Frozen Spire",
    "curveType": "superformula",
    "outer": 260,
    "inner": 0,
    "center": 0,
    "points": 1,
    "hue": 190,
    "spread": 0,
    "speed": 0.012,
    "layers": 5,
    "offset": "rotation",
    "offsetAmount": 0.1,
    "reverse": true,
    "dual": true,
    "secondary": "epitrochoid",
    "dualMode": "combine",
    "lineWeight": 1,
    "lineThinning": 0.4,
    "trail": 240,
    "scale": 1.1,
    "isBuiltIn": false
  },
  {
    "name": "Ghast Bloom",
    "curveType": "hypotrochoid",
    "outer": 300,
    "inner": 160,
    "center": 190,
    "points": 22,
    "hue": 280,
    "spread": 200,
    "speed": 0.014,
    "layers": 3,
    "offset": "rotation",
    "offsetAmount": 0.19,
    "reverse": true,
    "dual": false,
    "lineWeight": 1.1,
    "lineThinning": 0.6,
    "trail": 220,
    "scale": 1,
    "isBuiltIn": false
  }
];
