window.themes = [
  {
    "name": "Default",
    "curveType": "hypotrochoid",
    "outer": 180,
    "inner": 80,
    "center": 60,
    "points": 12,
    "scale": 1,
    "layers": 2,
    "offset": "radius",
    "offsetAmount": 0.06,
    "speed": 0.02,
    "trail": 120,
    "lineWeight": 1.6,
    "lineThinning": 0.7,
    "hue": 35,
    "spread": 120
  },
  {
    "name": "Rose",
    "curveType": "rose",
    "outer": 200,
    "inner": 100,
    "points": 7,
    "scale": 1.2,
    "layers": 1,
    "speed": 0.01,
    "trail": 200,
    "lineWeight": 1,
    "lineThinning": 0.5,
    "hue": 0,
    "spread": 60
  },
  {
    "name": "Lissajous",
    "curveType": "lissajous",
    "outer": 250,
    "inner": 200,
    "center": 0.5,
    "points": 1,
    "scale": 1,
    "layers": 1,
    "speed": 0.01,
    "trail": 300,
    "lineWeight": 2,
    "lineThinning": 0.2,
    "hue": 120,
    "spread": 0
  },
  {
    "name": "Petal Bloom",
    "curveType": "rose",
    "outer": 150,
    "inner": 40,
    "center": 120,
    "points": 8,
    "hue": 300,
    "spread": 60,
    "speed": 0.015,
    "layers": 2,
    "offset": "radius",
    "reverse": false,
    "dual": false
  },
  {
    "name": "Infinity Weave",
    "curveType": "lissajous",
    "outer": 220,
    "inner": 180,
    "center": 80,
    "points": 6,
    "hue": 200,
    "spread": 120,
    "speed": 0.01,
    "layers": 3,
    "offset": "phase",
    "reverse": true,
    "dual": true,
    "secondary": "hypotrochoid",
    "dualMode": "combine"
  },
  {
    "name": "Neon Spinner",
    "curveType": "epitrochoid",
    "outer": 180,
    "inner": 90,
    "center": 100,
    "points": 16,
    "hue": 50,
    "spread": 180,
    "speed": 0.025,
    "layers": 2,
    "offset": "rotation",
    "reverse": false,
    "dual": true,
    "secondary": "superformula",
    "dualMode": "blend"
  },
  {
    "name": "Deep Bloom",
    "curveType": "hypotrochoid",
    "outer": 200,
    "inner": 70,
    "center": 150,
    "points": 10,
    "hue": 160,
    "spread": 100,
    "speed": 0.018,
    "layers": 1,
    "offset": "radius",
    "reverse": false,
    "dual": false
  },
  {
    "name": "Starburst",
    "curveType": "rose",
    "outer": 260,
    "inner": 60,
    "center": 40,
    "points": 20,
    "hue": 10,
    "spread": 200,
    "speed": 0.02,
    "layers": 4,
    "offset": "rotation",
    "reverse": true,
    "dual": true,
    "secondary": "epitrochoid",
    "dualMode": "alternate"
  },
  {
    "name": "Cosmic Bloom",
    "curveType": "hypotrochoid",
    "outer": 250,
    "inner": 100,
    "center": 80,
    "points": 32,
    "hue": 280,
    "spread": 100,
    "speed": 0.005,
    "layers": 3,
    "offset": "phase",
    "reverse": true,
    "dual": false
  },
  {
    "name": "Electric Spiro",
    "curveType": "epitrochoid",
    "outer": 200,
    "inner": 50,
    "center": 120,
    "points": 3,
    "hue": 180,
    "spread": 30,
    "speed": 0.03,
    "layers": 1,
    "offset": "radius",
    "reverse": false,
    "dual": false
  },
  {
    "name": "Gentle Rose",
    "curveType": "rose",
    "outer": 150,
    "inner": 50,
    "center": 0,
    "points": 5,
    "hue": 330,
    "spread": 20,
    "speed": 0.01,
    "layers": 1,
    "offset": "radius",
    "reverse": false,
    "dual": false
  },
  {
    "name": "Dancing Lissajous",
    "curveType": "lissajous",
    "outer": 200,
    "inner": 150,
    "center": 0.2,
    "points": 1,
    "hue": 240,
    "spread": 0,
    "speed": 0.02,
    "layers": 1,
    "offset": "radius",
    "reverse": false,
    "dual": false
  },
  {
    "name": "Crystal Superformula",
    "curveType": "superformula",
    "outer": 200,
    "inner": 0,
    "center": 0,
    "points": 1,
    "hue": 180,
    "spread": 0,
    "speed": 0.01,
    "layers": 1,
    "offset": "radius",
    "reverse": false,
    "dual": false
  },
  {
    "name": "Harmonic Pendulum",
    "curveType": "harmonograph",
    "outer": 200,
    "inner": 100,
    "center": 0,
    "points": 1,
    "hue": 150,
    "spread": 0,
    "speed": 0.005,
    "layers": 1,
    "offset": "radius",
    "reverse": false,
    "dual": false
  },
  {
    "name": "Inner Fire",
    "curveType": "hypocycloid",
    "outer": 200,
    "inner": 80,
    "center": 0,
    "points": 1,
    "hue": 0,
    "spread": 30,
    "speed": 0.01,
    "layers": 1,
    "offset": "radius",
    "reverse": false,
    "dual": false
  },
  {
    "name": "Galactic Swirl",
    "curveType": "epicycloid",
    "outer": 150,
    "inner": 30,
    "center": 0,
    "points": 1,
    "hue": 270,
    "spread": 60,
    "speed": 0.01,
    "layers": 8,
    "offset": "rotation",
    "reverse": true,
    "dual": false
  },
  {
    "name": "Rolling Hills",
    "curveType": "cycloid",
    "outer": 0,
    "inner": 100,
    "center": 0,
    "points": 1,
    "hue": 120,
    "spread": 0,
    "speed": 0.01,
    "layers": 1,
    "offset": "radius",
    "reverse": false,
    "dual": false
  },
  {
    "name": "Comet's Tail",
    "curveType": "trochoid",
    "outer": 0,
    "inner": 100,
    "center": 150,
    "points": 1,
    "hue": 180,
    "spread": 0,
    "speed": 0.03,
    "trail": 300,
    "layers": 1,
    "offset": "radius",
    "reverse": false,
    "dual": false
  },

  /* ================================
     NEW THEMES ADDED BELOW
  ================================ */

  {
    "name": "Aurora Drift",
    "curveType": "hypotrochoid",
    "outer": 260,
    "inner": 110,
    "center": 140,
    "points": 18,
    "hue": 200,
    "spread": 160,
    "speed": 0.008,
    "layers": 3,
    "offset": "phase",
    "reverse": false,
    "dual": false
  },
  {
    "name": "Solar Bloom",
    "curveType": "rose",
    "outer": 300,
    "inner": 80,
    "center": 60,
    "points": 12,
    "hue": 35,
    "spread": 90,
    "speed": 0.015,
    "layers": 4,
    "offset": "rotation",
    "reverse": true,
    "dual": true,
    "secondary": "epitrochoid",
    "dualMode": "blend"
  },
  {
    "name": "Quantum Echo",
    "curveType": "lissajous",
    "outer": 240,
    "inner": 190,
    "center": 0.3,
    "points": 1,
    "hue": 260,
    "spread": 0,
    "speed": 0.006,
    "layers": 2,
    "offset": "phase",
    "reverse": false,
    "dual": true,
    "secondary": "superformula",
    "dualMode": "alternate"
  },
  {
    "name": "Mirage Spiral",
    "curveType": "epitrochoid",
    "outer": 220,
    "inner": 40,
    "center": 150,
    "points": 22,
    "hue": 150,
    "spread": 200,
    "speed": 0.02,
    "layers": 3,
    "offset": "radius",
    "reverse": true,
    "dual": false
  },
  {
    "name": "Velvet Pulse",
    "curveType": "superformula",
    "outer": 180,
    "inner": 0,
    "center": 0,
    "points": 1,
    "hue": 320,
    "spread": 0,
    "speed": 0.012,
    "layers": 2,
    "offset": "rotation",
    "reverse": false,
    "dual": false
  },
  {
    "name": "Atomic Flower",
    "curveType": "rose",
    "outer": 210,
    "inner": 60,
    "center": 40,
    "points": 24,
    "hue": 90,
    "spread": 140,
    "speed": 0.018,
    "layers": 5,
    "offset": "phase",
    "reverse": true,
    "dual": true,
    "secondary": "hypotrochoid",
    "dualMode": "combine"
  },
  {
    "name": "Midnight Lens",
    "curveType": "hypocycloid",
    "outer": 220,
    "inner": 45,
    "center": 0,
    "points": 1,
    "hue": 260,
    "spread": 40,
    "speed": 0.01,
    "layers": 1,
    "offset": "rotation",
    "reverse": false,
    "dual": false
  },
  {
    "name": "Ion Drift",
    "curveType": "epicycloid",
    "outer": 260,
    "inner": 70,
    "center": 0,
    "points": 1,
    "hue": 180,
    "spread": 120,
    "speed": 0.02,
    "layers": 6,
    "offset": "phase",
    "reverse": true,
    "dual": false
  },
  {
    "name": "Dream Tides",
    "curveType": "trochoid",
    "outer": 0,
    "inner": 140,
    "center": 90,
    "points": 1,
    "hue": 280,
    "spread": 20,
    "speed": 0.009,
    "trail": 250,
    "layers": 2,
    "offset": "radius",
    "reverse": false,
    "dual": false
  },
  {
    "name": "Hypernova",
    "curveType": "epitrochoid",
    "outer": 300,
    "inner": 100,
    "center": 200,
    "points": 30,
    "hue": 20,
    "spread": 260,
    "speed": 0.04,
    "layers": 3,
    "offset": "rotation",
    "reverse": true,
    "dual": true,
    "secondary": "superformula",
    "dualMode": "blend"
  }
];